
YEAR = $(shell date '+%Y')
DAY  = $(shell date '+%d')

TITLE = YOUR TITLE GOES HERE

FILE_PART_ONE = part-1.js
FILE_PART_TWO = part-2.js
FILE_README = README.md

TEMPLATE_DIRECTORY = _templates/
TEMPLATE_FILE_README = $(TEMPLATE_DIRECTORY)$(FILE_README)
TEMPLATE_FILE_PART_ONE = $(TEMPLATE_DIRECTORY)$(FILE_PART_ONE)
TEMPLATE_FILE_PART_TWO = $(TEMPLATE_DIRECTORY)$(FILE_PART_TWO)

OUTPUT_DIRECTORY = $(YEAR)/$(DAY)/
OUTPUT_FILE_README = $(OUTPUT_DIRECTORY)$(FILE_README)
OUTPUT_FILE_PART_ONE = $(OUTPUT_DIRECTORY)$(FILE_PART_ONE)
OUTPUT_FILE_PART_TWO = $(OUTPUT_DIRECTORY)$(FILE_PART_TWO)

all: $(OUTPUT_FILE_README) $(OUTPUT_FILE_PART_ONE) $(OUTPUT_FILE_PART_TWO)

$(OUTPUT_FILE_README): $(TEMPLATE_FILE_README)
	mkdir -p $(OUTPUT_DIRECTORY)
	cp $^ $@
	sed -i -e 's/{YEAR}/$(YEAR)/g' -e 's/{DAY}/$(DAY)/g' -e 's/{TITLE}/$(TITLE)/g' $@

$(OUTPUT_FILE_PART_ONE): $(TEMPLATE_FILE_PART_ONE)
	cp $^ $@;

$(OUTPUT_FILE_PART_TWO): $(TEMPLATE_FILE_PART_TWO)
	cp $^ $@;

.PHONY: clean
clean:
	rm -rf $(OUTPUT_DIRECTORY)

